To use https://aws.amazon.com/s3/[Amazon S3], you need the following dependency:

dependency:io.micronaut.objectstorage:micronaut-object-storage-aws[]

Refer to the https://micronaut-projects.github.io/micronaut-aws/latest/guide[Micronaut AWS documentation] for more
information about credentials and region configuration.

The object storage specific configuration options available are:

include::{includedir}configurationProperties/io.micronaut.objectstorage.aws.AwsS3Configuration.adoc[]

For example:

.`src/main/resources/application-ec2.yml`
[configuration]
----
include::doc-examples/example-java/src/test/resources/application-ec2.yml[]
----

The concrete implementation of `ObjectStorageOperations` is api:objectstorage.aws.AwsS3Operations[].
It also implements api:objectstorage.MultipartObjectStorageOperations[] for multipart upload lifecycle support.

You can also resolve objects through Micronaut's `ResourceLoader` abstraction:

* Named storage URI: `pictures://avatars/logo.png`
* AWS alias URI: `s3://pictures-bucket/avatars/logo.png`

The `s3:` alias only resolves buckets that are already configured under `micronaut.object-storage.aws`.

== Advanced configuration

For configuration properties other than the specified above, you can add bean to your application that implements
https://docs.micronaut.io/latest/guide/#events[`BeanCreatedEventListener`]. For example:

[source,java]
----
include::doc-examples/example-java/src/main/java/example/aws/S3ClientBuilderCustomizer.java[tags="class"]
----

See api:objectstorage.MultipartObjectStorageOperations[] and the <<multipartUploads,Multipart Uploads>> guide for the
portable multipart lifecycle contract.

TIP: See the guide for https://guides.micronaut.io/latest/micronaut-object-storage-aws.html[Use the Micronaut Object Storage API to Store Files in Amazon S3] to learn more.
