To use https://azure.microsoft.com/en-gb/services/storage/blobs/[Azure Blob Storage], you need the following dependency:

dependency:io.micronaut.objectstorage:micronaut-object-storage-azure[]

Refer to the https://micronaut-projects.github.io/micronaut-azure/latest/guide[Micronaut Azure documentation] for more
information about authentication options.

The object storage specific configuration options available are:

include::{includedir}configurationProperties/io.micronaut.objectstorage.azure.AzureBlobStorageConfiguration.adoc[]

For example:

.`src/main/resources/application-azure.yml`
[configuration]
----
include::doc-examples/example-java/src/test/resources/application-azure.yml[]
----

The concrete implementation of `ObjectStorageOperations` is api:objectstorage.azure.AzureBlobStorageOperations[].

You can also resolve objects through Micronaut's `ResourceLoader` abstraction:

* Named storage URI: `pictures://avatars/logo.png`
* Azure alias URI: `azb:storageaccount://pictures/avatars/logo.png`

The `azb:` alias only resolves configured storages, matching the account name from `endpoint` together with the
configured container name.

== Advanced configuration

For configuration properties other than the specified above, you can add bean to your application that implements
https://docs.micronaut.io/latest/guide/#events[`BeanCreatedEventListener`]. For example:

[source,java]
----
include::doc-examples/example-java/src/main/java/example/azure/BlobServiceClientBuilderCustomizer.java[tags="class"]
----
