To use https://cloud.google.com/storage[Google Cloud Storage], you need the following dependency:

dependency:io.micronaut.objectstorage:micronaut-object-storage-gcp[]

Refer to the https://micronaut-projects.github.io/micronaut-gcp/latest/guide[Micronaut GCP documentation] for more
information about configuring your GCP project.

The object storage specific configuration options available are:

include::{includedir}configurationProperties/io.micronaut.objectstorage.googlecloud.GoogleCloudStorageConfiguration.adoc[]

The module-wide configuration options available are:

include::{includedir}configurationProperties/io.micronaut.objectstorage.googlecloud.GoogleCloudStorageModuleConfiguration.adoc[]

For example:

.`src/main/resources/application-gcp.yml`
[configuration]
----
include::doc-examples/example-java/src/test/resources/application-gcp.yml[]
----

The concrete implementation of `ObjectStorageOperations` is api:objectstorage.googlecloud.GoogleCloudStorageOperations[].

You can also resolve objects through Micronaut's `ResourceLoader` abstraction:

* Named storage URI: `pictures://avatars/logo.png`
* Google Cloud alias URI: `gs://pictures-bucket/avatars/logo.png`

The `gs:` alias only resolves buckets that are already configured under `micronaut.object-storage.gcp`.

== Advanced configuration

The Google Cloud Storage client uses the JSON-over-HTTP transport by default. To use the gRPC transport, set
`grpc-enabled` to `true`:

[configuration]
----
micronaut:
  object-storage:
    gcp:
      grpc-enabled: true
----

For configuration properties other than the specified above, you can add a bean to your application that implements
https://docs.micronaut.io/latest/guide/#events[`BeanCreatedEventListener`]. For example:

[source,java]
----
include::doc-examples/example-java/src/main/java/example/gcp/StorageOptionsBuilderCustomizer.java[tags="class"]
----

TIP: See the guide for https://guides.micronaut.io/latest/micronaut-object-storage-gcp.html[Use the Micronaut Object Storage API to Store Files in Google Cloud Storage] to learn more.
