To get started, you need to declare a dependency for the actual cloud provider you are using. See the actual cloud
provider documentation for more details:

* <<aws, Amazon S3>>.
* <<azure, Azure Blob Storage>>.
* <<gcp, Google Cloud Storage>>.
* <<oracleCloud, Oracle Cloud Infrastructure (OCI) Object Storage>>.

Then, you can inject in your controllers/services/etc. a bean of type api:objectstorage.ObjectStorageOperations[].

The following example uses AWS S3:

snippet::example.ProfileService[project-base="doc-examples/example", source="main", indent="0", tags="beginclass,endclass"]

If you have multiple object storages configured, it is possible to select which one to work with via
https://docs.micronaut.io/latest/guide/#qualifiers[bean qualifiers].

For example, given the following configuration:

.`src/main/resources/application-ec2.yml`
[source,yaml]
----
micronaut:
  object-storage:
    aws:
      pictures:
        name: pictures-bucket
      logos:
        name: logos-bucket
----

You need to use `@Named("pictures")` or `@Named("logos")` to specify which of the object storages you want to use.

== Uploading files

snippet::example.ProfileService[project-base="doc-examples/example", source="main", indent="0", tags="upload"]

<1> You can use any of the api:objectstorage.UploadRequest[] static methods to build an upload request.
<2> The upload operation returns an api:objectstorage.UploadResponse[].

== Uploading files with Customization

You can use the method `upload(UploadRequest, Consumer)` of api:objectstorage.ObjectStorageOperations[] to customize an upload:

[source,java]
----
include::object-storage-aws/src/test/groovy/io/micronaut/objectstorage/aws/AwsS3OperationsUploadWithConsumerSpec.groovy[tag="consumer", indent="0"]
----

== Retrieving files

snippet::example.ProfileService[project-base="doc-examples/example", source="main", indent="0", tags="retrieve"]

<1> The retrieve operation returns an api:objectstorage.ObjectStorageEntry[], from which you can get an `InputStream`.

== Deleting files

snippet::example.ProfileService[project-base="doc-examples/example", source="main", indent="0", tags="delete"]
