plugins {
    id 'io.micronaut.build.internal.module'
    id "io.micronaut.build.internal.objectstorage-base"
    id("org.sonatype.gradle.plugins.scan")
}
String ossIndexUsername = System.getenv("OSS_INDEX_USERNAME") ?: project.properties["ossIndexUsername"]
String ossIndexPassword = System.getenv("OSS_INDEX_PASSWORD") ?: project.properties["ossIndexPassword"]
boolean sonatypePluginConfigured = ossIndexUsername != null && ossIndexPassword != null
if (sonatypePluginConfigured) {
    ossIndexAudit {
        username = ossIndexUsername
        password = ossIndexPassword
        excludeCoordinates = [
                "org.threeten:threetenbp:1.7.2", // no version patched https://ossindex.sonatype.org/component/pkg:maven/org.threeten/threetenbp
        ]
    }
}
dependencies {
    annotationProcessor mn.micronaut.inject.java
    implementation mn.micronaut.inject
    implementation mn.micronaut.context
}
