plugins {
    id 'io.micronaut.build.internal.module'
    id "io.micronaut.build.internal.objectstorage-base"
    id("org.sonatype.gradle.plugins.scan")
}
String ossIndexUsername = System.getenv("OSS_INDEX_USERNAME") ?: project.properties["ossIndexUsername"]
String ossIndexPassword = System.getenv("OSS_INDEX_PASSWORD") ?: project.properties["ossIndexPassword"]
boolean sonatypePluginConfigured = ossIndexUsername != null && ossIndexPassword != null
ossIndexAudit {
if (sonatypePluginConfigured) {
    username = ossIndexUsername
    password = ossIndexPassword
}
    excludeCoordinates = [
            "io.projectreactor.netty:reactor-netty-http:1.2.10" // https://ossindex.sonatype.org/vulnerability/CVE-2025-22227?component-type=maven&component-name=io.projectreactor.netty%2Freactor-netty-http&utm_source=ossindex-client&utm_medium=integration&utm_content=1.8.2
    ]
}
dependencies {
    annotationProcessor mn.micronaut.inject.java
    implementation mn.micronaut.inject
    implementation mn.micronaut.context
}
