/*
 * Copyright 2017-2025 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.objectstorage.local;

import io.micronaut.core.annotation.Internal;
import io.micronaut.objectstorage.request.PresignRequest;
import jakarta.inject.Singleton;

import java.time.Instant;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Simple in-memory registry that keeps track of pre-authorized requests generated by the
 * {@link LocalStorageOperations#presign(io.micronaut.objectstorage.request.PresignRequest)}
 * implementation.
 *
 * <p>The information is kept only for the lifetime of the JVM and removed on first use to emulate
 * a single-shot signed URL.</p>
 */
@Singleton
@Internal
class LocalPresignStore {
    /**
     * Information associated with a generated token.
     *
     * @param key        The object key.
     * @param operation  The authorised operation.
     * @param expiration When the token expires.
     */
    record Entry(String key, PresignRequest.Operation operation, Instant expiration) {
        boolean isExpired() {
            return Instant.now().isAfter(expiration);
        }
    }

    private final ConcurrentHashMap<String, Entry> TOKENS = new ConcurrentHashMap<>();

    /**
     * Registers a new pre-authorised request and returns the generated token.
     *
     * @param key        Object key.
     * @param operation  Operation.
     * @param expiration Expiration instant.
     * @return The generated opaque token.
     */
    String register(String key, PresignRequest.Operation operation, Instant expiration) {
        String token = UUID.randomUUID().toString();
        TOKENS.put(token, new Entry(key, operation, expiration));
        return token;
    }

    /**
     * Retrieves and removes the stored entry associated with the supplied token.
     *
     * @param token Token.
     * @return The {@link Entry} if present and not expired, or an empty optional otherwise.
     */
    Optional<Entry> consume(String token) {
        Entry entry = TOKENS.remove(token);
        if (entry == null || entry.isExpired()) {
            return Optional.empty();
        }
        return Optional.of(entry);
    }

    /**
     * Explicitly removes the stored entry associated with the supplied token,
     * effectively invalidating the pre-signed request.
     *
     * @param token Token to invalidate.
     */
    void remove(String token) {
        TOKENS.remove(token);
    }
}
