name: Google Cloud CI
on:
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
    paths:
      - 'object-storage-gcp/**'
      - 'object-storage-core/**'
      - 'object-storage-tck/**'
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
    paths:
      - 'gradle/**'
      - 'object-storage-gcp/**'
      - 'object-storage-core/**'
      - 'object-storage-tck/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['25']
    permissions:
      contents: 'read'
    steps:
       # https://github.com/actions/virtual-environments/issues/709
      - name: Free disk space
        run: |
         sudo rm -rf "/usr/local/share/boost"
         sudo rm -rf "$AGENT_TOOLSDIRECTORY"
         sudo apt-get clean
         df -h
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        if: github.event_name != 'pull_request'
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Build with Gradle (trusted events)
        if: github.event_name != 'pull_request'
        run: |
          ./gradlew :micronaut-object-storage-gcp:test --no-daemon --parallel --continue
        env:
           TESTCONTAINERS_RYUK_DISABLED: true
           GCLOUD_TEST_PROJECT_ID: ${{ secrets.GCLOUD_TEST_PROJECT_ID }}
           GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
           GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
           GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
           PREDICTIVE_TEST_SELECTION: "false"
      - name: Build with Gradle (pull requests)
        if: github.event_name == 'pull_request'
        run: |
          ./gradlew :micronaut-object-storage-gcp:test --no-daemon --parallel --continue
        env:
           TESTCONTAINERS_RYUK_DISABLED: true
           PREDICTIVE_TEST_SELECTION: "true"
      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@bccf2e31636835cf0874589931c4116687171386 # v6.4.0
        with:
          check_name: Java CI / Test Report (${{ matrix.java }})
          report_paths: '**/build/test-results/test/TEST-*.xml'
          check_retries: 'true'
